name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (for example, adjust this depending on your tech stack)
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Deploy to server (using SSH)"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Create .ssh directory and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Add SSH private key to the instance
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add server host key to known_hosts to prevent "Host key verification failed" error
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Run the deployment script
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST 'bash -s' < deploy.sh

